### ISSUE TITLE
How does this code work?

### ISSUE THREAD

**Issue by epower** [fiesta-iot/testbed.tpi#1]
Can you provide an example of how this code should ideally be deployed in order to try it out?

So far I've tried 
```
mvn verify
mvn package

```
which generates a war file. I then add the war file to a tomcat host and while the war appears to run, I don't see any output when I got to http://localhost:8080/tpi.api.tps/ I get a 404 with no trace on the server logs.

**Comment by NSeydoux** [comment]
Hi, 
I'm not expert in these technologies, so I'm not sure my answer will be of any help, but the jaxrs activator has an ApplicationPath annotation that seems to be required to access ressources. The URL should look something like http://localhost:8080/rest/tps. A get on this URL should return the welcome message defined in the TpiApiTestbedProviderServices.java welcomeMessage() function.
Is it solving your issue ?

**Comment by nkef** [comment]
Hi epower, 

You can find directions on how to build and deploy the war file at the handbook. Did you had a look there?

**Comment by nkef** [comment]
From the Handbook:

4.3.3.3	Install & Run
The prototype has been implemented as a Maven-based web application. Below WILDFLY_HOME indicates the root directory of the WildFly distribution, and PROJECT_HOME indicates the root directory of the project (tpi.api.tps).
In order to build the prototype, run the following command in PROJECT_HOME:
mvn clean package
Finally, in order to deploy the prototype, run the following command in PROJECT_HOME:
mvn wildfly:deploy
The last step assumes that WildFly is already running on the machine where you run the command. 
The produced, from the build process above (mvn clean package), project can be found within PROJECT_HOME/target/ folder and is the tpi.api.tps.war file. Alternatively copy the produced (from the build process above) tpi.api.tps.war file from the target directory (PROJECT_HOME/target/), into the WILDFLY_HOME/standalone/deployments directory of the WildFly  distribution, in order to be automatically deployed.
If the deployment has been successfully completed, the implemented web services described in the section above will be exposed under the following URLs:
•	http://[HOST]:[PORT]/tpi.api.tps/rest/tps/getLastObservations
•	http://[HOST]:[PORT]/tpi.api.tps/rest/tps/getObservations
•	http://[HOST]:[PORT]/tpi.api.tps/rest/tps/pushLastObservations
•	http://[HOST]:[PORT]/tpi.api.tps/rest/tps/stopPushOfObservations

**Comment by epower** [comment]
Hi there, yes - I've found it and can confirm that its running ok. Thank you for your help. I've put a pull request in that adds the above instructions to the README.md
